# Generated by Django 2.2.15 on 2020-08-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_content', '0064_auto_20200606_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300)),
                ('expiration_date', models.DateTimeField()),
                ('profile_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_content.ProfileBrand')),
            ],
        ),
    ]
